### ISSUE TITLE
generate-carbon-impact-statement script

### ISSUE THREAD

**Issue by rems75** [Breakend/experiment-impact-tracker#15]
Hi there,

Cool library! 
Got this issue when running:
`generate-carbon-impact-statement tracker "USA"`

The script returns this error:
`loading region bounding boxes for computing carbon emissions region, this may take a moment...
 454/454... rate=556.09 Hz, eta=0:00:00, total=0:00:00, wall=15:15 UTCC
Done!
Traceback (most recent call last):

File "/home/retachet/.conda/envs/homer/bin/generate-carbon-impact-statement", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  
File "/home/retachet/ExperimentImpactTracker/experiment-impact-tracker/scripts/generate-carbon-impact-statement", line 235, in <module>
    sys.exit(main(sys.argv[1:]))
  
File "/home/retachet/ExperimentImpactTracker/experiment-impact-tracker/scripts/generate-carbon-impact-statement", line 177, in main
    extracted_info = gather_additional_info(info, log_dir)
  
File "/home/retachet/ExperimentImpactTracker/experiment-impact-tracker/experiment_impact_tracker/utils.py", line 102, in gather_additional_info
    cpu_seconds = _get_cpu_hours_from_per_process_data(json_array)
  
File "/home/retachet/ExperimentImpactTracker/experiment-impact-tracker/experiment_impact_tracker/utils.py", line 94, in _get_cpu_hours_from_per_process_data
    cpu_point = datapoint["cpu_time_seconds"]

KeyError: 'cpu_time_seconds'`

**Comment by rems75** [comment]
Update on this. Seems like my setup currently doesn't support RAPL, so the data does not contain ''cpu_time_seconds'' or "rapl_estimated_attributable_power_draw" which then crashes the statement generation.

**Comment by Breakend** [comment]
I see, yes, we assume RAPL is available. In your use case would you like only GPU measurements if RAPL is not available?

**Comment by Breakend** [comment]
Closing due to inactivity, but if having GPU-only recording is a requested feature, please open a new issue!
