### ISSUE TITLE
Getting a minimal example working

### ISSUE THREAD

**Issue by leondz** [Breakend/experiment-impact-tracker#2]
I'm trying to get a "hello, world"-type report out. So far I have:

test.py
```
#!/usr/bin/env python3

from experiment_impact_tracker.compute_tracker import ImpactTracker
import time

tracker = ImpactTracker('logs')
tracker.launch_impact_monitor()

time.sleep(2)
```

This populates the logs dir with: 
```
$ ll logs/impacttracker/
total 92
drwxr-xr-x 2 leon leon  4096 Apr  9 19:54 ./
drwxr-xr-x 3 leon leon  4096 Apr  9 18:31 ../
-rw-r--r-- 1 leon leon     0 Apr  9 19:54 data.json
-rw-r--r-- 1 leon leon  2673 Apr  9 18:47 impact_tracker_log.log
-rw-r--r-- 1 leon leon 77938 Apr  9 19:54 info.pkl
```

When I try to get a report, this is thrown
```
$ generate-carbon-impact-statement logs/ "DNK"
loading region bounding boxes for computing carbon emissions region, this may take a moment...
 454/454... rate=702.29 Hz, eta=0:00:00, total=0:00:00, wall=20:08 CETT
Done!
/usr/local/bin/generate-carbon-impact-statement:37: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('display.max_colwidth', -1)
/usr/local/lib/python3.6/dist-packages/experiment_impact_tracker/data_utils.py:26: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  return json_normalize(json_array, max_level=max_level), json_array
Traceback (most recent call last):
  File "/home/leon/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'timestamp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/generate-carbon-impact-statement", line 233, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/bin/generate-carbon-impact-statement", line 177, in main
    extracted_info = gather_additional_info(info, log_dir)
  File "/usr/local/lib/python3.6/dist-packages/experiment_impact_tracker/utils.py", line 107, in gather_additional_info
    time_differences = df["timestamp"].diff()
  File "/home/leon/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/leon/.local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'timestamp'
```

Looking further, I think `df` should be populated from `data.json` in the `DATAPATH` by `load_data_into_frame` in data_utils.py, but I can't figure out where in the code writes to this file. It's 0-length in my case, so doesn't have the `timestamp` key. Not sure if this is a bug or user error - how can I set up a minimal end-to-end example?

**Comment by Breakend** [comment]
Hi, because we implement a polling method and assume long running experiments, it will likely take more than two seconds to log something. Maybe this isn't intuitive so we might have to rethink this. So basically there's a sleep timer in the main loop that's one second https://github.com/Breakend/experiment-impact-tracker/blob/master/experiment_impact_tracker/compute_tracker.py#L111

But there are other metrics within the loop that also require a sleep or multiple samples (for example polling nvidia-smi for power polls for 5 seconds and takes the average power. Similarly, intel's rapl interface polls for another second, and i think the disk speed writes for a half a second. So I'd say maybe just put a sleep for 10-15 seconds and let me know if that doesn't work?

If you have an issues with this we're also open to suggestions if you have better ways to efficiently query the inner metrics in the loop.

**Comment by leondz** [comment]
Fixed. Thanks!
