### ISSUE TITLE
Support for abruptly stopped experiments

### ISSUE THREAD

**Issue by cifkao** [Breakend/experiment-impact-tracker#37]
I interrupted an experiment and now when I run `generate-carbon-impact-statement`, it crashes with:
```pytb
Traceback (most recent call last):
  File "venv/bin/generate-carbon-impact-statement", line 233, in <module>
    sys.exit(main(sys.argv[1:]))
  File "venv/bin/generate-carbon-impact-statement", line 177, in main
    extracted_info = gather_additional_info(info, log_dir)
  File "venv/lib/python3.6/site-packages/experiment_impact_tracker/utils.py", line 101, in gather_additional_info
    exp_len = datetime.timestamp(info["experiment_end"]) - \
KeyError: 'experiment_end'
```

I think this situation can be quite common, so the tracker should be able to recover from it (e.g. taking the last logged timestamp if `experiment_end` is not available) instead of crashing.

**Comment by Breakend** [comment]
This should be fixed in #51, we now allow the last logged timestamp as an estimate of the experiment length with a warning saying that this may not be accurate.
