### ISSUE TITLE
NotImplementedError: Unexpected top level domain for RAPL package. Not yet supported.

### ISSUE THREAD

**Issue by Hasseneby** [Breakend/experiment-impact-tracker#69]
Hello Everyone,

I have an issue running the experiment example. I saw that the issue was solved, but i didn't understand how i can fix it.

`loading` region bounding boxes for computing carbon emissions region, this may take a moment...
 454/454... rate=658.04 Hz, eta=0:00:00, total=0:00:00, wall=16:46 CETT
Done!
experiment_impact_tracker.compute_tracker.ImpactTracker - WARNING - Gathering system info for reproducibility...
experiment_impact_tracker.compute_tracker.ImpactTracker - WARNING - Done initial setup and information gathering...
/tmp/tmpy37szyx0
experiment_impact_tracker.compute_tracker.ImpactTracker - WARNING - Starting process to monitor power
experiment_impact_tracker.compute_tracker.ImpactTracker - WARNING - Datapoint timestamp took 3.695487976074219e-05 seconds
experiment_impact_tracker.compute_tracker.ImpactTracker - ERROR - Encountered exception within power monitor thread!
experiment_impact_tracker.compute_tracker.ImpactTracker - ERROR -   File "/home/hasseneby/.local/lib/python3.8/site-packages/experiment_impact_tracker/compute_tracker.py", line 105, in launch_power_monitor
    _sample_and_log_power(log_dir, initial_info, logger=logger)
  File "/home/hasseneby/.local/lib/python3.8/site-packages/experiment_impact_tracker/compute_tracker.py", line 69, in _sample_and_log_power
    results = header["routing"]["function"](process_ids, logger=logger, region=initial_info['region']['id'], log_dir=log_dir)
  File "/home/hasseneby/.local/lib/python3.8/site-packages/experiment_impact_tracker/cpu/intel.py", line 133, in get_rapl_power
    raise NotImplementedError(

Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hasseneby/.local/lib/python3.8/site-packages/experiment_impact_tracker/utils.py", line 68, in process_func
    raise e
  File "/home/hasseneby/.local/lib/python3.8/site-packages/experiment_impact_tracker/utils.py", line 62, in process_func
    ret = func(q, *args, **kwargs)
  File "/home/hasseneby/.local/lib/python3.8/site-packages/experiment_impact_tracker/compute_tracker.py", line 105, in launch_power_monitor
    _sample_and_log_power(log_dir, initial_info, logger=logger)
  File "/home/hasseneby/.local/lib/python3.8/site-packages/experiment_impact_tracker/compute_tracker.py", line 69, in _sample_and_log_power
    results = header["routing"]["function"](process_ids, logger=logger, region=initial_info['region']['id'], log_dir=log_dir)
  File "/home/hasseneby/.local/lib/python3.8/site-packages/experiment_impact_tracker/cpu/intel.py", line 133, in get_rapl_power
    raise NotImplementedError(
NotImplementedError: Unexpected top level domain for RAPL package. Not yet supported.
Pass: 9
Traceback (most recent call last):
  File "Documents/impacttracker.py", line 71, in <module>
    my_experiment()
  File "Documents/impacttracker.py", line 64, in my_experiment
    tracker.get_latest_info_and_check_for_errors()
  File "/home/hasseneby/.local/lib/python3.8/site-packages/experiment_impact_tracker/compute_tracker.py", line 224, in get_latest_info_and_check_for_errors
    raise ex_type(message)
NotImplementedError: Unexpected top level domain for RAPL package. Not yet supported. (in subprocess)
  File "/home/hasseneby/.local/lib/python3.8/site-packages/experiment_impact_tracker/utils.py", line 62, in process_func
    ret = func(q, *args, **kwargs)
  File "/home/hasseneby/.local/lib/python3.8/site-packages/experiment_impact_tracker/compute_tracker.py", line 105, in launch_power_monitor
    _sample_and_log_power(log_dir, initial_info, logger=logger)
  File "/home/hasseneby/.local/lib/python3.8/site-packages/experiment_impact_tracker/compute_tracker.py", line 69, in _sample_and_log_power
    results = header["routing"]["function"](process_ids, logger=logger, region=initial_info['region']['id'], log_dir=log_dir)
  File "/home/hasseneby/.local/lib/python3.8/site-packages/experiment_impact_tracker/cpu/intel.py", line 133, in get_rapl_power
    raise NotImplementedError( `

My region is France and i don't use GPU for the test. Running on the newest Ubunto version 20.04.
Thanks for your return :)

**Comment by Breakend** [comment]
Hi, it looks like your CPU is returning something that we don't know how to process. Can you send us your CPU version?

**Comment by Hasseneby** [comment]
Hi, thanks for your answer. 
Here is my CPU infos : 
Version: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
	Voltage: 1.1 V
	External Clock: 100 MHz
	Max Speed: 2000 MHz
	Current Speed: 1800 MHz
	Status: Populated, Enabled
	Upgrade: Socket BGA1356
	L1 Cache Handle: 0x0007
	L2 Cache Handle: 0x0008
	L3 Cache Handle: 0x0009
	Serial Number: None
	Asset Tag: None
	Part Number: None
	Core Count: 4
	Core Enabled: 4
	Thread Count: 8

**Comment by Omerkvc** [comment]
> Hi, thanks for your answer. Here is my CPU infos : Version: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz Voltage: 1.1 V External Clock: 100 MHz Max Speed: 2000 MHz Current Speed: 1800 MHz Status: Populated, Enabled Upgrade: Socket BGA1356 L1 Cache Handle: 0x0007 L2 Cache Handle: 0x0008 L3 Cache Handle: 0x0009 Serial Number: None Asset Tag: None Part Number: None Core Count: 4 Core Enabled: 4 Thread Count: 8

heyy, did you figure out this problem, I have also same problem
